extends: 'stylelint-config-standard-scss'
rules:
  string-quotes: null
  value-list-comma-newline-after: null
  declaration-colon-newline-after: null
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
